#!/bin/bash -e

PREREQ=""
prereqs()
{
    echo "${PREREQ}"
}
case "${1}" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/bin/bt-adapter
copy_exec /usr/bin/bt-agent
copy_exec /usr/bin/bt-network
copy_exec /usr/sbin/bridge
copy_file config /etc/initramfs-tools/dnsmasq.conf /etc/dnsmasq.conf
